### ISSUE TITLE
Error when trying to start proxy

### ISSUE THREAD

**Issue by MrReasonable** [a85/PostmanProxy#2]
When I run the command: `16:45 $ pmproxy save --tcp_connection true`

The following output appears on the console:

``` sh
Proxy running at 8080
Press Ctrl+C to stop the proxy
Traceback (most recent call last):
  File "/usr/local/bin/pmproxy", line 9, in <module>
    load_entry_point('PostmanProxy==0.1.5', 'console_scripts', 'pmproxy')()
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 91, in main
    start_creator_proxy(args)
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 45, in start_creator_proxy
    cacert = os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'
```

Also, a similar error appears if you try to run the proxy in filter mode:

``` sh
16:49 $ pmproxy filter
Press Ctrl+C to stop the proxy
Traceback (most recent call last):
  File "/usr/local/bin/pmproxy", line 9, in <module>
    load_entry_point('PostmanProxy==0.1.5', 'console_scripts', 'pmproxy')()
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 93, in main
    start_filter_proxy(args)
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 66, in start_filter_proxy
    cacert = os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'
```

In both cases, it looks like the cause of the problem is 

``` python
config = proxy.ProxyConfig(
        cacert = os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
    )
```

Is there a reason that this is path is hard coded?

**Comment by isadon** [comment]
Getting this same error as well. is there a way to fix this?

**Comment by tylercollier** [comment]
I'm getting the same thing. I'm on Ubuntu 12.04.

That path is in two places: [here](https://github.com/a85/PostmanProxy/blob/bb075fa5fc48a26939ab8819f700e08794a63046/postmanproxy/main.py#L45) and [here](https://github.com/a85/PostmanProxy/blob/bb075fa5fc48a26939ab8819f700e08794a63046/postmanproxy/main.py#L66).

Where does that cert file come from? How can I get it?

**Comment by tylercollier** [comment]
Ha, I didn't realize @IanDominey already identified both places. My bad.

**Comment by horstvanbommel** [comment]
I'm also getting this error. Using Mac OS X 10.10.2.

The cert file exists. No idea what's causing trouble.

**Comment by UzLA** [comment]
Fresh Ubuntu 14.10 install. Same problem here. BTW  mitmproxy-ca.pem is missing  after install. Creation of mitmproxy-ca.pem is not reflected in the Postman Interceptor instructions (http://www.getpostman.com/docs/capture).

**Comment by dzuluaga** [comment]
+1 Mac Yosemite

**Comment by pidries** [comment]
+1 
PostmanProxy version 0.1.5 doesn't seem to be compatible with mitmproxy version 0.11.3.

**Comment by GitFree** [comment]
+1 Mac Yosemite

**Comment by paulononaka** [comment]
+1 Mac OS X 10.9.4

**Comment by kayvannj** [comment]
+1

**Comment by tashian** [comment]
+1 Mac Yosemite

**Comment by mlvea** [comment]
+1

**Comment by cmohnacs** [comment]
+1 OS X 10.10.3

**Comment by pidries** [comment]
Try peppy's fork: https://github.com/peppy/PostmanProxy.

I was able to get it up and running after fixing some imports.

**Comment by kayvannj** [comment]
I pulled in peppy's fork and fixed couple other errors. 
Here is the repo https://github.com/kayvannj/PostmanProxy

Make sure you do these steps instead of the ones in the https://www.getpostman.com/docs/capture
- use `python postmanproxy/main.py save --tcp_connection true` instead of `pmproxy save --tcp_connection true`
- start your postman app and connect the proxy setting to port 5005
- now you can browse on a device with set proxy and you will see the captures on postman
- the SSL certification problems are not related to this thread

**Comment by fonsocloud** [comment]
```
$ python postmanproxy/main.py save --tcp_connection true
Traceback (most recent call last):
  File "postmanproxy/main.py", line 1, in <module>
    from postman.collection import Collection
ImportError: No module named collection
```

**Comment by kayvannj** [comment]
@fonsocloud This error has been fixed on my fork, you should clone this: https://github.com/kayvannj/PostmanProxy

**Comment by starchow** [comment]
Hi @kayvannj,
I have just clone your fork but I see the same error as @fonsocloud 

```
$ python postmanproxy/main.py save --tcp_connection true   
Traceback (most recent call last):
  File "postmanproxy/main.py", line 1, in <module>
    from postman.collection import Collection
ImportError: No module named collection
```

Please help me, I really want to use PostmanProxy!
Thanks!

**Comment by starchow** [comment]
Haha, 
I found that the name of Collection.py was wrong, It must be collection.py
Now I can run it.

**Comment by kayvannj** [comment]
@starchow I'm sorry for that, that was because of known issue with github that doesn't recognize  change of caps and doesn't commit them. I'll fix it.

**Comment by starchow** [comment]
Thank you @kayvannj 
Hope your pull request will be merged soon!

**Comment by q42jaap** [comment]
This is still a problem!!!

**Comment by Boztown** [comment]
I'm getting this issue with Mac El Capitan with python/pip installed via brew. 

``` sh
✗ python -V
Python 2.7.10

✗ pip -V
pip 7.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)

✗ pmproxy save --tcp_connection true
Proxy running at 8080
Press Ctrl+C to stop the proxy
Traceback (most recent call last):
  File "/usr/local/bin/pmproxy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 91, in main
    start_creator_proxy(args)
  File "/usr/local/lib/python2.7/site-packages/postmanproxy/main.py", line 45, in start_creator_proxy
    cacert = os.path.expanduser("~/.mitmproxy/mitmproxy-ca.pem")
TypeError: __init__() got an unexpected keyword argument 'cacert'
```

**Comment by Boztown** [comment]
A bit more info for anyone interested:

This file "~/.mitmproxy/mitmproxy-ca.pem" gets created the first time you run `mitmproxy`. Run that in the terminal and you'll get these files generated. However, that didn't solve my issue. I also tried loosening the permissions on those cert files but no luck.

**Comment by Boztown** [comment]
So @kayvannj's fork seems to start up fine (thank you) but when I actually go to proxy into it I seem to crash mitmproxy. Something like this (there's more though):

```
Traceback (most recent call last):
  File "/Users/rbosinger/PostmanProxy/postmanproxy/postman/collection_creator_proxy.py", line 112, in handle_request
    request2.init_from_proxy(msg)
  File "/Users/rbosinger/PostmanProxy/postmanproxy/postman/request.py", line 139, in init_from_proxy
    self.headers = self.get_headers(proxy_request.headers)
  File "/Users/rbosinger/PostmanProxy/postmanproxy/postman/request.py", line 129, in get_headers
    for k, v in headers:
ValueError: too many values to unpack
Sent response
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/server.py", line 120, in handle
    root_layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/proxy/modes/http_proxy.py", line 10, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/tls.py", line 272, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 130, in __call__
    layer()
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 352, in __call__
    self.send_response_to_client(flow)
  File "/usr/local/lib/python2.7/site-packages/libmproxy/protocol/http.py", line 416, in send_response_to_client
    if not (self.supports_streaming and flow.response.stream):
AttributeError: 'HTTPResponse' object has no attribute 'response'

mitmproxy has crashed!
Please lodge a bug report at: https://github.com/mitmproxy/mitmproxy
```

Darn. This would have been handy. I don't think I can get into that any further though.

**Comment by mlalty** [comment]
You could fork [this repo](https://github.com/noodleOne/PostmanProxy) and feel free ;)

**Comment by nrktkt** [comment]
+1 Linux Mint 17.2

**Comment by NathanMgnet** [comment]
I have a similar problem.
When I try to start the mitmproxy I get this error in file _constructs.py (line 69):

TypeError: **init**() got an unexpected keyword argument 'length_field'

**Comment by jackmiller334** [comment]
@NathanMgnet I have the same error too when launching mitmproxy

Running on Linux Mint 18

**Comment by NathanMgnet** [comment]
I'll try.
Thanks

**Comment by jackmiller334** [comment]
Hey @NathanMgnet, I've managed to get it working. Turns out its an issue with constructs. 

if you head into

```
/usr/local/lib/python2.7/dist-packages/mitmproxy/contrib/tls/_constructs.py
```

and rename every instance of 

```
length_field
```

to 

```
lengthfield
```

you should get it running again. 

As an example

```
    PascalString("name", length_field=UBInt16("length")),
```

Should become

```
    PascalString("name", lengthfield=UBInt16("length")),
```

Hope that helps.

**Comment by NathanMgnet** [comment]
Hi @jackmiller334 
It worked!
Thanks
