### ISSUE TITLE
ImportError: No module named libmproxy

### ISSUE THREAD

**Issue by sryze** [a85/PostmanProxy#6]
When I run `pmproxy save --tcp_connection true` the following error occurs:

```
Traceback (most recent call last):
  File "/Users/sergey/Library/Python/2.7/bin/pmproxy", line 9, in <module>
    load_entry_point('PostmanProxy==0.1.5', 'console_scripts', 'pmproxy')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Users/sergey/Library/Python/2.7/lib/python/site-packages/postmanproxy/main.py", line 2, in <module>
    from postman.collection_creator_proxy import CollectionCreatorProxy
  File "/Users/sergey/Library/Python/2.7/lib/python/site-packages/postmanproxy/postman/collection_creator_proxy.py", line 1, in <module>
    from libmproxy import controller, proxy
ImportError: No module named libmproxy
```

I installed PostmanProxy with `pip install --user PostmanProxy`. I also tried re-installing mitmproxy a few times but that didn't help.

OS: Mac OS X 10.11.5 
pip version: pip 8.1.2 from /Library/Python/2.7/site-packages (python 2.7)

**Comment by ubuntudroid** [comment]
Have exactly the same. :(

**Comment by ubuntudroid** [comment]
Opened an issue here: https://github.com/postmanlabs/postman-app-support/issues/2133
